### ISSUE TITLE
Staking ODIN on a VPS - Makefile:4374: recipe for target 'libbitcoin_server_a-init.o' failed

### ISSUE THREAD

**Issue by fgeorge** [odinblockchain/Odin#13]
### Describe the issue
Unable to setup headless ODIN on a VPS (DO). make command fails
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
followed the steps from the [guide](https://github.com/odinblockchain/wiki/wiki/Staking-ODIN-on-a-VPS)

`~/github/odin# NPROC=$(nproc)`
`~/github/odin# make -j$NPROC`
```Making all in src
make[1]: Entering directory '/root/github/odin/src'
make[2]: Entering directory '/root/github/odin/src'
  CXX      odind-odind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4374: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/root/github/odin/src'
Makefile:7892: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/github/odin/src'
Makefile:681: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1```


### Expected behavior
Should be able to run `odind` successfully

### What version of ODIN Core are you using?
cloned the master branch (as of 11/07/2018) as described in the setup guide on 
### Machine specs:
DO $5 / month VPS

### Any extra information that might be useful in the debugging process.
Please let m know what debug files are required. I can update it here

**Comment by thijslnl** [comment]
That's probably due to your VPS running out of RAM. How much RAM do you have an did you set up a SWAP file?

I see you write you've got the $5/m DigitalOcean Droplet. You will need to set up a SWAP file to run the installer on those. Try the following code to add a 1GB SWAP file.

` # Setup the system SWAP memory usage to make sure we have enough memory`
` # to get through odind creation later on.`
` # More info: https://support.rackspace.com/how-to/create-a-linux-swap-file/`
`sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000`
`sudo mkswap /var/swap.img`
`sudo chmod 600 /var/swap.img`
`sudo swapon /var/swap.img`

**Comment by fgeorge** [comment]
yes. I guess I missed that step from the guide. It's working fine now
